spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # SQL 파라미터 확인

collect:
  tag-collect-url: https://api.codenary.co.kr/techstacks
  wanted:
    list-url-prefix: https://www.wanted.co.kr
    list-url-cursor: /api/chaos/navigation/v1/results?job_group_id=518&country=kr&job_sort=job.latest_order&years=-1&locations=all&limit=20
    detail-url: https://www.wanted.co.kr/api/chaos/jobs/v3/{uniqueJobId}/details